---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eph
  labels:
    app: eph
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eph
  template:
    metadata:
      labels:
        app: eph
    spec:
      containers:
      - name: eph
        image: torosent/eph
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:     
          - name: COSMOSDB_NAME
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: COSMOSDB_NAME
          - name: COSMOSDB_KEY
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: COSMOSDB_KEY
          - name: NAMESPACE
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: NAMESPACE
          - name: EH_NAME
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: EH_NAME
          - name: SAS_KEY_NAME
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: SAS_KEY_NAME
          - name: SAS_KEY
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: SAS_KEY
          - name: STORAGE_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: STORAGE_CONN_STRING
          - name: STORAGE_CONTAINER
            valueFrom:
              secretKeyRef:
                name: ehworkers
                key: STORAGE_CONTAINER
                