---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: messagesender
  labels:
    app: messagesender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagesender
  template:
    metadata:
      labels:
        app: messagesender
    spec:
      containers:
      - name: messagesender
        image: torosent/messagesender
        env:   
          - name: QUEUE_NAME
            value:
          - name: SB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: casestudy1
                key: sb
          
                