apiVersion: v1
kind: Secret
metadata:
  name: casestudy1
type: Opaque
data:
  clientid: 
  clientsecret: 
  subscriptionid: 
  tenantid: 
  sb:


# To prepare secret, we need to encode it to Base64
# echo -n "admin" | base64 or use https://www.base64encode.org/